name: Continue Deployment for web
on:
  workflow_call:
    inputs:
      environment:
        description: "Which environment to deploy.Should be set ahead in repo config."
        type: string
        required: true
      channelId:
        description: "Whether to deploy to live channel."
        type: string
        required: true

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    if: ${{ inputs.environment == 'prod' }}
    environment: prod

    steps:
      - name: Checkout Code (for retriving Action Scripts)
        uses: actions/checkout@v4

      - uses: "./.github/workflows/web-deploy.yml"
        with:
          ci-workflow-id: ${{ github.event.workflow_run.id }}
          channelId: ${{ inputs.channelId }}
          projectId: ${{ secrets.SG_WEB_FB_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDGLASS_CCCE4 }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}

  deploy_staging:
    runs-on: ubuntu-latest

    if: ${{ inputs.environment == 'staging' }}
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: "./.github/workflows/web-deploy.yml"
        with:
          ci-workflow-id: ${{ github.event.workflow_run.id }}
          channelId: ${{ inputs.channelId }}
          projectId: ${{ secrets.SG_WEB_FB_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDGLASS_DEV_2BC90 }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
