name: Continue Integration for web

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: cd packages/web && bun run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build-artifact
          path: packages/web/dist/
